# Generated by Django 2.2.6 on 2019-10-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_of_pages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
